### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by AdminOdd** [rodrigograca31/Samaritan#15]
I created an A.I how can i get the A.I to speak in your Samaritan browser?

**Comment by rodrigograca31** [comment]
@AdminOdd Normally a issued with the title "need help" would be ignored, but....

You can edit the phrase list file or send a message via the msg GET parameter....

**Comment by AdminOdd** [comment]
Mr Rodrigograca Thank you so much for replying, Not alot of people due but thank you so much!!!!!

But one more thing D: How would i send a message via the msg? and get a parameter D: i use API.AI :D I really do need help, Because you created something so amazing!!! And i just wanted to like add some of my ideas to it D: if you don't mind!

**Comment by rodrigograca31** [comment]
@AdminOdd like this: http://rodrigograca31.github.io/Samaritan/?msg=Hi%20AdminOdd!

**Comment by AdminOdd** [comment]
Yes but like putting your own commands rather then typing it on url

**Comment by rodrigograca31** [comment]
Without using the URL you need to edit the file `phraselist.js`

**Comment by AdminOdd** [comment]
After i redit the phrase list how do i upload it to the website again?

**Comment by rodrigograca31** [comment]
What website? 
This one? [http://rodrigograca31.github.io/Samaritan/](http://rodrigograca31.github.io/Samaritan/)
You would need to send a pull request, but since your phrases are probably not from the Series it would be rejected, so you need to run the website in your PC by opening the `index.html` file.

**Comment by AdminOdd** [comment]
I know where that file is but how would i run it? with what atleast

**Comment by Feliix42** [comment]
Just open the page in your Web Browser of Choice.

**Comment by rodrigograca31** [comment]
Yes, like @Feliix42 said. :)
