### ISSUE TITLE
Service worker caching

### ISSUE THREAD

**Issue by AlexandruSimandi** [rodrigograca31/Samaritan#21]
Could the caching be removed? The browser already does it's own internal smart caching (downloads sources only if changed).
I am forced to do ctrl+f5 after every minor change.

**Comment by rodrigograca31** [comment]
Ok.... I will do this in a couple minutes...

**Comment by rodrigograca31** [comment]
Done....

**Comment by rodrigograca31** [comment]
BTW, what browser are you using? (and version?)

Because this was not an issue for me....
