### ISSUE TITLE
I love what you did to Samaritan.

### ISSUE THREAD

**Issue by AConcernedThirdParty** [rodrigograca31/Samaritan#25]
[Video explains all.](http://4.sendvid.com/6c9p6lux.mp4)

**Comment by rodrigograca31** [comment]
lol, this should not be a issue....
and there's currently a bug....

**Comment by AdminOdd** [comment]
emmmm its way better at https://alexandrusimandi.github.io/Samaritan/ Smh

**Comment by rodrigograca31** [comment]
My version was updated and has everything that one has...

**Comment by AdminOdd** [comment]
just now? or already

**Comment by AdminOdd** [comment]
Hey! It's me. Remember 2 years ago we had a Samaritan Idea! I think we can
actually now create a new interface using the samaritan idea as our "chat"
I just discovered the perfect tool for It! We could actually make this a
website now! Contact me at disgraceddoor6@icloud.com!!!!
