### ISSUE TITLE
msg parameter doesn't work

### ISSUE THREAD

**Issue by alexmelyon** [rodrigograca31/Samaritan#26]
http://rodrigograca31.github.io/Samaritan/?msg=Hi%20Reddit

**Comment by rodrigograca31** [comment]
@AlexandruSimandi can you fix it?

**Comment by AlexandruSimandi** [comment]
it does work but it cannot be seen behind the intro

**Comment by AlexandruSimandi** [comment]
fixed, requires more thorough testing since i wrote it after 3 beers

**Comment by rodrigograca31** [comment]
Looks good... I will merge it tomorrow morning....
