### ISSUE TITLE
License

### ISSUE THREAD

**Issue by amirmohsen** [rodrigograca31/Samaritan#5]
What's the license on this project? I'd like to use it in one of my apps. I might even contribute to it if I can find the time. Pretty cool, by the way! :+1:

**Comment by rodrigograca31** [comment]
License? Basically there is no license...
Copyleft? In other words, I don't mind if you use my code, I only ask that if possible you contribute to the main project or mention it...

**Comment by rodrigograca31** [comment]
I'm closing this issue.

Can you provide me a link where I can learn the basics of licences and which ones to choose?

**Comment by ama56-unikent** [comment]
http://choosealicense.com/ provides a simple guide to licenses. And you can use this article to learn how to add a license to a github repo: https://help.github.com/articles/open-source-licensing/
I usually prefer MIT for most open-source projects.

**Comment by rodrigograca31** [comment]
I will add this link to the topic: http://creativecommons.org/choose/
