### ISSUE TITLE
Unresponsive, when I change the phrases

### ISSUE THREAD

**Issue by zacharisharris** [rodrigograca31/Samaritan#7]
Whenever I change the text from the phrase list, the page becomes unresponsive. I mean it does show the animation with the line and the triangle but no text when I click it?

**Comment by rodrigograca31** [comment]
Hi @zacharisharris, you have closed the issue... have you found the problem?

**Comment by zacharisharris** [comment]
Hey man, I sure did there was some problem with the browsers.
By the way can you help me make it change theme according to time of day? I
mean I have created 2 themes (Day & Night) and have implemented some code
but can't get it to work..
Are you willing to help?

Thanks in advance,
Harris

2015-04-24 13:42 GMT+03:00 Rodrigo Graça <notifications@github.com>:

**Comment by rodrigograca31** [comment]
I'm a bit occupied, but I can give you some tips:

If you already have the themes done, you can do:
```javascript
var dt = new Date();
var hour = dt.getHours();
```
To get the hour of the day and then you can apply the theme accordingly...
